In [1]:
import tensorflow as tf
import numpy as np


In [2]:
array = np.ones(shape=(5,3,2))
# il yen a 5 qui cotinnent 3 qui contiennet 2 

In [3]:
print(array)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [7]:
shape = tf.shape(array)
print(shape)

tf.Tensor([5 3 2], shape=(3,), dtype=int32)
